-- slim-qms-checksheets.sql (2026-07-30) — re-author 4 shop-floor check sheets to the
-- evidence pattern: photo + tap-tick outcome + sign. Procedure lives in the docs,
-- not restated on the form. DATA-ONLY (updates QmsForms.definition) — NO restart.
-- Requires create-qms-forms.sql + seed-qms-forms-phase2.sql to have run first.

UPDATE QmsForms SET title = N'Fabrication: Weld & Dimensional Check', definition = N'{"folder": "checksheets", "fields": [{"key": "proc", "type": "note", "text": "Check the assembly against the drawing and the fabrication procedure (Company Docs ▸ Quality ▸ Procedures). This record is EVIDENCE the check was done — take a photo, mark the outcome, sign, save."}, {"key": "job", "label": "Job / contract", "type": "job", "required": true}, {"key": "drawing_asm", "label": "Drawing / assembly checked", "type": "text", "required": true}, {"key": "weld_quality", "label": "Weld quality", "type": "yesno", "yesLabel": "Good quality", "noLabel": "Poor — needs rework", "required": true}, {"key": "dim_check", "label": "Dimensional check", "type": "yesno", "yesLabel": "Pass", "noLabel": "Fail", "required": true}, {"key": "photo", "label": "Photo evidence", "type": "photo"}, {"key": "checked_by", "label": "Checked by", "type": "text", "required": true}, {"key": "notes", "label": "Notes (only if rework needed)", "type": "textarea", "rows": 2}, {"key": "signature", "label": "Signature", "type": "signature"}]}' WHERE form_code = 'BAMA FAB 001';
UPDATE QmsForms SET title = N'Final Inspection & Release', definition = N'{"folder": "checksheets", "fields": [{"key": "proc", "type": "note", "text": "Final check before the item leaves the shop. Confirm the finished work matches the drawing and the coating spec, photograph it, sign, save. Full procedure: Company Docs ▸ Quality."}, {"key": "job", "label": "Job / contract", "type": "job", "required": true}, {"key": "assemblies", "label": "Assemblies released", "type": "text", "required": true}, {"key": "final_check", "label": "Final visual & dimensional", "type": "yesno", "yesLabel": "Pass", "noLabel": "Fail", "required": true}, {"key": "surface_ok", "label": "Surface treatment to spec", "type": "yesno", "yesLabel": "OK", "noLabel": "Not OK", "allowNa": true, "required": true}, {"key": "photo", "label": "Photo of finished work", "type": "photo"}, {"key": "released_by", "label": "Released by", "type": "text", "required": true}, {"key": "notes", "label": "Notes (optional)", "type": "textarea", "rows": 2}, {"key": "signature", "label": "Signature", "type": "signature"}]}' WHERE form_code = 'BAMA REL 001';
UPDATE QmsForms SET title = N'Material Receiving', definition = N'{"folder": "checksheets", "fields": [{"key": "proc", "type": "note", "text": "Check delivered material against the order and the mill / test certificate. Photograph the certificate — that photo is the evidence. Heat-number traceability is recorded separately against assemblies in the job."}, {"key": "job", "label": "Job / stock (optional)", "type": "job"}, {"key": "supplier", "label": "Supplier", "type": "text"}, {"key": "material_desc", "label": "Material received", "type": "text", "required": true}, {"key": "cert_ok", "label": "Cert supplied & matches order", "type": "yesno", "yesLabel": "Yes", "noLabel": "No", "required": true}, {"key": "cert_photo", "label": "Photo of material certificate", "type": "photo"}, {"key": "condition", "label": "Condition on arrival", "type": "yesno", "yesLabel": "Acceptable", "noLabel": "Damaged / reject", "required": true}, {"key": "received_by", "label": "Received by", "type": "text", "required": true}, {"key": "notes", "label": "Notes (only if a problem)", "type": "textarea", "rows": 2}]}' WHERE form_code = 'BAMA MAT 001';
UPDATE QmsForms SET title = N'Site Daily / Erection Record', definition = N'{"folder": "checksheets", "fields": [{"key": "proc", "type": "note", "text": "Daily erection record — evidence of who was on site, what went up, and that the site was left safe. Photograph the day''s progress. Method statement / RAMS: on the job."}, {"key": "job", "label": "Job / contract", "type": "job", "required": true}, {"key": "work_date", "label": "Date", "type": "date", "required": true}, {"key": "crew", "label": "Crew on site", "type": "personnel"}, {"key": "progress", "label": "Work done today", "type": "textarea", "rows": 3, "required": true}, {"key": "safe_ok", "label": "Site left safe & secure", "type": "yesno", "yesLabel": "Yes", "noLabel": "No", "required": true}, {"key": "photo", "label": "Site photo", "type": "photo"}, {"key": "supervisor", "label": "Supervisor", "type": "text", "required": true}, {"key": "signature", "label": "Signature", "type": "signature"}]}' WHERE form_code = 'BAMA SITE 001';
